### ISSUE TITLE
Consistency issues in documentation / file naming

### ISSUE THREAD

**Issue by BBerastegui** [BBVA/patton-server#12]
Hi!

There is a small lack of consistency in the documentation: `https://patton.readthedocs.io/deployment.html#deploy-with-internal-database`

The `docker-compose` file is referred in the documentation as `docker-compose.yml` while the file in the repo is `docker-compose.yaml`.

Whatever you prefer to change :)

**Comment by hhurtado** [comment]
Related to deprecated v1.
