### ISSUE TITLE
Vulnerability feeds are now available only as JSON

### ISSUE THREAD

**Issue by rizumu** [BBVA/patton-server#15]
Per the timeline provided in the XML feed retirement announcement we will be implementing Phase 3 of the XML retirement plan on Wednesday October 16th.

    * This is one week later than originally planned.
    * The feeds will no longer be accessible to any users or automated processes. 
    * Users will need to begin ingesting the JSON 1.1 Feeds for vulnerability information.

old location as XML:
https://static.nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2019.xml.gz

new location as JSON:
https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.json.gz

**Comment by hhurtado** [comment]
Related to deprecated v1.
