### ISSUE TITLE
Error updating the DB in kali 

### ISSUE THREAD

**Issue by carlospolop** [BBVA/patton-server#3]
I had problems updating the data base in a Kali 2017.3 machine using a Docker machine as Postgres DB:

![imagen](https://user-images.githubusercontent.com/17181413/36214081-c2a28b3e-11a8-11e8-997d-1b9ee860c031.png)

The value of the `version` variable of my machine was:
![imagen](https://user-images.githubusercontent.com/17181413/36217069-cc039238-11b0-11e8-9384-8f4a863cb148.png)

I solved this patching the line 46 of /usr/local/lib/python3.6/dist-packages/asyncpg/serverversion.py
I changed:
from: `[int(p) for p in parts][:3]`
to: `versions = [int(''.join(s for s in str(p) if s.isdigit())) for p in parts[:3]]`

**Comment by cr0hn** [comment]
Witch version of Postgres are you using?

**Comment by carlospolop** [comment]
10.2 
I followed the guide and I downloaded a new docker machine with Postgres just running:
`docker run -d -p 5432:5432 -e POSTGRES_USER=patton -e POSTGRES_DB=patton postgres`
And the Postgres version that is installed by default is this one (10.2)

**Comment by cr0hn** [comment]
It's appears that it's a known fail with the driver and Ubuntu:

https://github.com/MagicStack/asyncpg/issues/250

I just run released a new version of patton-server with an small fix. Then I tried:

`> docker run -d -p 5432:5432 -e POSTGRES_USER=patton -e POSTGRES_DB=patton postgres:10.1`
`> patton-server init-db && patton-server update-db`

Above commands works well for me. Could you run again with Postgres version 10.1 and the new version of Patton-server. To update on execute:

`pip install -U patton-server`

**Comment by carlospolop** [comment]
Perfect, following that instructions there was not any errors.
Thank you very much for the help and for the software!
